# Generated by Django 3.1.3 on 2020-11-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=10000)),
                ('position', models.CharField(max_length=20)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
